; Listing generated by Microsoft (R) Optimizing Compiler Version 19.14.26430.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\ian28\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
